{% set name = "multipledispatch" %}
{% set version = "1.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5c839915465c68206c3e9c473357908216c28383b425361e5d144594bf85a7e0

build:
  number: 0
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python

test:
  requires:
    - pip
  imports:
    - multipledispatch
    - multipledispatch.utils
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"

about:
  home: https://github.com/mrocklin/multipledispatch
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Multiple dispatch in Python
  description: |
    This implementation of multiple dispatch is efficient, mostly complete,
    performs static analysis to avoid conflicts, and provides optional
    namespace support.
  doc_url: https://multiple-dispatch.readthedocs.io
  dev_url: https://github.com/mrocklin/multipledispatch

extra:
  recipe-maintainers:
    - pmlandwehr
