travis:
  secure:
    BINSTAR_TOKEN: MxFDJy6rWYh0Z0rTGANKajnlph9xc/BlrsECVFQTLVMm7Ok8ywPm0X13QtNv0g14BvV2tBkVJX/gG/cXCuGtch3LNsCxZcslNX6AXSzkc4W0Y7IhKvA7bbbLVUBXqb6rM4WRHazIWJNrWRhlAZ6gUoeUFTgHWuYjTDwlOJZ79Qkv1FmOGInhOrBsBmnRHWCLlXUnAbXDfRRSUHMn3by/nzaoLqIzSMHoCnEkvIqhb8v/jF/iHBwCjAN8GbF4SM1R9/Wv/kr23vkkDyYuXNdcRcweehW5792gewzNkLB/yG0ltHxgyPQFbxkPhFvrLFxsh1GCRTdYtM28ZlNzjQxJumLCKRiRz+/rXc5EtN2XR4uXI6FUi5dGFMyD2gdhl4ZjeA71+PwjfZeIyqoSa07rcf+Np5xw7AMHzeBEpMgIRKNR0ogt3dHCBzcLiU1VoYre5SWH3vi8OFcwO6FTdzHjYKTH+ljAHPLVjLYPTUA0ZLQorIvrlgK+yX+sblSiCM5RyEota0scnuDoNZrG7jFuY3HlSRuw1HduIBEUNJiysUCEBI7d5Byv9BlkKu/AiLHVThxucux7sUEguh38+fXRSTI63HQ0tZ/JRY1qTODRfZhyCxihyDSsHHcMh6+FtMW/JWOjsoJAuYE9VnUjEjL57An+CHdQkoSc0at1FLM0sPQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
