travis:
  secure:
    BINSTAR_TOKEN: QkGs2XpLvTf+FpyZIuGCeH7/4jSl8St+cX8ICx5k1QsUgQM93NJtvKByKxEx2+vqWxhn6pMp+Nx0rGNmI8DSgc/tlSZxxMdnEn3f+FOr7eKx5ouzvYJeY4CisSf3lvJvJDpXLf/D0Mhikp5BviHe2I3dFuEaUIZp84qWFrDJPpkbgzRyw2gg6EMBkvnq1mUHzs7PAtq1DgST4CMLlqsFJkI8nokB892F7jmLPxNGfml1Ege5eCrXC+ZPqknGj0Ag4cD+knKwm4RUDOuco4AdGfm/1EeNEuURfTVfHiXGBUq+Gv7W7fxL3hGEgIFi2u2/xxJJlctuJI50lEuGEnz69DDakFxid6Ll+Hxx86VwKrgBJv9XAAGm6UwIZuczMo3/BNWEbnMUYgVXO6kGdEOguxoY01xomdrIYbJ36yI777Mtz+2WPFUyWMSbR5fD6uoybNehqO6CwFS1yhV2aI9SLIP42F/VgpAEzgjcSKO+jueS0lTPYm8vM0K/TlErVqC9tVvuQspW6AvVRbyjCWMz6G0RGggEMa9DYni3eYb3UmCuilsONJSxgtsyhfxxv/pgIyBna+OGqO2iu5k+bXL3UExlwBlIfUnijq9xt7nCRa/8zc3bobABYZLr/YjgHI6cHxGswGEaIrUsKYkUYw2EYXhjh6/Mp9euQA23HUlBX6w=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
